name: Kode kloud_First_example

on:
  push:
    paths:
      - '.github/workflows/frst_exap.yaml'


jobs:
  first_job:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: welcome message
        run: echo "Wellcome to my first Kode Kloud Job"

      - name: List files
        run: ls

      - name: Read files
        run: cat README.md   
      