name: Generate ASCII Artwork

on:
  push:
    paths:
      - '.github/workflows/generate-ascii.yaml'
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: List files
          run: ls  
  
        - name: Executing Shell Script 
          run: ./ascii-script.sh
