name: Exploring Variables and Secrets

on: 
    push:
        paths:
            - '.github/workflows/variable-secret.yaml'
jobs:
    docker:
        runs-on: ubuntu-latest 
        steps:
            - name: Docker Build 
              env: 
                CONTAINER_REGISTRY: docker.io
                CONTAINER_USERNAME:  siddharth1
                IMAGE_NAME: github-actions-nginx 
              run: echo docker build -t $CONTAINER_REGISTRY/$Docker_USERNAME/$IMAGE_NAME:latest .
            
            - name: Docker Login 
              env: 
                CONTAINER_PASSWORD: s3CurePas$$w0rd
                DOCKER_USERNAME: siddharth1
              run: echo docker login --username}$DOCKER_USERNAME --password}$DOCKER_PASSWORD
            
            - name: DOCKER Publish
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: siddharth1
                IMAGE_NAME: github-actions-nginx
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
            
            
    deploy:       
       needs: docker
       runs-on: ubuntu-latest
       steps:
         - name: Docker Run
           env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: siddharth1
                IMAGE_NAME: github-actions-nginx
           run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:LATEST